// Admin_Frontend/src/components/SignUp.vue
<<template>
  <div class="signUpPage">
    <h1>Sign Up</h1>

    <form @submit="register" class="signUpForm">
      <span>{{ spanFn }}</span>
      <input type="text" v-model="firstname" placeholder="First Name" />

      <span>{{ spanLn }}</span>
      <input type="text" v-model="lastname" placeholder="Last Name" />

      <span></span>
      <input type="text" v-model="username" placeholder="Username" />

      <span>{{ spanPwd }}</span>
      <input type="password" v-model="password" placeholder="Password" />

      <span>{{ spanCPwd }}</span>
      <input
        type="password"
        v-model="confirmPassword"
        placeholder="Confirm Password"
      />

      <span>{{ spanEmail }}</span>
      <input type="text" v-model="email" placeholder="Email" />

      <span></span>
      <input type="text" v-model="contactNum" placeholder="Contact Number" />

      <span></span>
      <input type="text" v-model="address" placeholder="Address" />

      <button>Sign Up</button>
    </form>

    <p>Already have an account? <a href="">Log in</a></p>
  </div>
</template>

<script setup>
import { ref, watch } from "vue";

const firstname = ref("");
const lastname = ref("");
const username = ref("");
const email = ref("");
const password = ref("");
const confirmPassword = ref("");
const contactNum = ref("");
const address = ref("");

const spanFn = ref("");
const spanLn = ref("");
const spanPwd = ref("");
const spanCPwd = ref("");
const spanEmail = ref("");

function checker() {
  const namePattern = /^[A-Za-z\s]+$/;
  const regex =
    /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()-.+])[a-zA-Z\d!@#$%^&*()-.+]{8,}$/;
  const emailPattern = /^[^\s@]+@gmail\.com$/;

  // First name validation
  if (firstname.value === "") {
    spanFn.value = "";
  } else if (!namePattern.test(firstname.value)) {
    spanFn.value = "Invalid";
  } else {
    spanFn.value = "";
  }

  // Last name validation
  if (lastname.value === "") {
    spanLn.value = "";
  } else if (!namePattern.test(lastname.value)) {
    spanLn.value = "Invalid";
  } else {
    spanLn.value = "";
  }

  // Password validation
  if (password.value === "") {
    spanPwd.value = "";
  } else if (!regex.test(password.value)) {
    spanPwd.value = "Invalid";
  } else {
    spanPwd.value = "";
  }

  // Confirm password validation
  if (confirmPassword.value === "") {
    spanCPwd.value = "";
  } else if (confirmPassword.value !== password.value) {
    spanCPwd.value = "Passwords do not match";
  } else {
    spanCPwd.value = "";
  }

  // Email validation
  if (email.value === "") {
    spanEmail.value = "";
  } else if (!emailPattern.test(email.value)) {
    spanEmail.value = "Invalid email";
  } else {
    spanEmail.value = "";
  }
}

async function register(event) {
  event.preventDefault();

  const emailPattern = /^[^\s@]+@gmail\.com$/;
  const namePattern = /^[A-Za-z\s]+$/;

  if (
    !firstname.value ||
    !lastname.value ||
    !username.value ||
    !email.value ||
    !password.value ||
    !contactNum.value ||
    !address.value
  ) {
    console.log("Needs All Credentials to be filled");
    return;
  }

  if (
    !namePattern.test(firstname.value) ||
    !namePattern.test(lastname.value) ||
    confirmPassword.value !== password.value ||
    !emailPattern.test(email.value)
  ) {
    console.log("Invalid Credentials");
    return;
  }

  const userInfo = {
    firstname: firstname.value,
    lastname: lastname.value,
    username: username.value,
    email: email.value,
    password: password.value,
    contactNum: contactNum.value,
    address: address.value,
  };

  try {
    const response = await fetch(
      "http://localhost:3500/userRegister/addUser",
      {
        method: "POST",
        headers: {
          "Content-type": "application/json",
        },
        body: JSON.stringify(userInfo),
      }
    );

    if (!response.ok) {
      throw new Error("Failed Add User");
    }

    const updates = await response.json();
    console.log(updates);

    // Reset fields
    firstname.value = "";
    lastname.value = "";
    email.value = "";
    username.value = "";
    password.value = "";
    confirmPassword.value = "";
    address.value = "";
    contactNum.value = "";
  } catch (err) {
    console.error(err);
  }
}

// Vue equivalent of useEffect dependency array
watch(
  [firstname, lastname, password, confirmPassword, email],
  checker
);
</script>

<style scoped>
/* Keep your existing styles or move your CSS here */
</style>

// User_Frontend/src/pages/SignUp.jsx
import React, { useState, useEffect} from 'react';

function SignUp(){
    const [firstname, setFirstname] = useState('');
    const [lastname, setLastname] = useState('');
    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [contactNum, setContacNum] = useState('');
    const [address, setAddress] = useState('');

    const [spanFn, setSpanFn] = useState('');
    const [spanLn, setSpanLn] = useState('');
    const [spanPwd, setSpanPwd] = useState('');
    const [spanCPwdm, setSpanCPwd] = useState('');
    const [spanEmail, setSpanEmail] = useState('');



    function checker(){
        const namePattern = /^[A-Za-z\s]+$/;
        const regex = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()-.+])[a-zA-Z\d!@#$%^&*()-.+]{8,}$/;
        const emailPattern = /^[^\s@]+@gmail\.com$/;

        if(firstname === ''){
            setSpanFn('');
        }
        else if(!namePattern.test(firstname)){
            setSpanFn('Invalid');
        } else{
            setSpanFn('');
        }

        if(lastname === ''){
            setSpanLn('');
        }
        else if(!namePattern.test(lastname)){
            setSpanLn('Invalid');
        } else {
            setSpanLn('');
        }


        if(password === ''){
            setSpanPwd('');
        }
        else if(!regex.test(password)){
            setSpanPwd('Invalid');
        } else {
            setSpanPwd('');
        }


        if(confirmPassword === ''){
            setSpanCPwd('');
        }
        else if(confirmPassword !== password){
            setSpanCPwd('Passwords do not match');
        } else {
            setSpanCPwd('');
        }


        if(email === ''){
            setSpanEmail('');
        }
        else if(!emailPattern.test(email)){
            setSpanEmail('Invalid email');
        } else {
            setSpanEmail('');

        }
    }

    async function register(event){
        event.preventDefault();
        const emailPattern = /^[^\s@]+@gmail\.com$/;
        const namePattern = /^[A-Za-z\s]+$/;
        const regex = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()-.+])[a-zA-Z\d!@#$%^&*()-.+]{8,}$/;

        if(firstname === '' || lastname === '' || username === '' || email === '' || password=== '' || contactNum === '' || address === ''){
            return console.log('Needs All Credentials to be filled');
        }
     
        if(!namePattern.test(firstname) || !namePattern.test(lastname) || confirmPassword !== password || !emailPattern.test(email)){
            return console.log("Invalid Credentials");

        }

        const userInfo ={
            firstname,
            lastname,
            username,
            email,
            password,
            contactNum,
            address
        }

        try{
            const response = await fetch('http://localhost:3500/userRegister/addUser',{
                method: 'POST',
                headers: {
                    'Content-type': 'application/json'
                },
                body: JSON.stringify(userInfo)
            });

            if(!response.ok){
                throw new Error('Failed Add User');
            }

            const updates = await response.json();
            console.log(updates)

            setFirstname('');
            setLastname('');
            setEmail('');
            setUsername('');
            setPassword('');
            setConfirmPassword('');
            setAddress('');
            setContacNum('');
            
        } catch (err){
            console.error(err);
        }
    }

    useEffect(() => {
    checker();
    }, [firstname, lastname, password, confirmPassword, email]);

    return(
        <div className='signUpPage'>
            <h1>Sign Up</h1>
            <form onSubmit={register} className='signUpForm'>
                <span>{spanFn}</span>
                <input type='text' value={firstname} onChange={(e) => setFirstname(e.target.value)} placeholder="First Name"></input>
                <span>{spanLn}</span>
                <input type='text' value={lastname} onChange={(e) => setLastname(e.target.value)} placeholder="Last Name"></input>
                <span></span>
                <input type='text' value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Username"></input>
                <span>{spanPwd}</span>
                <input type='password' value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password"></input>
                <span>{spanCPwdm}</span>
                <input type='password' value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Confirm Password"></input>
                <span>{spanEmail}</span>
                <input type='text' value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email"></input>
                <span></span>
                <input type='text' value={contactNum} onChange={(e) => setContacNum(e.target.value)} placeholder="Contact Number"></input>
                <span></span>
                <input type='text' value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Address"></input>
                <button> Sign Up</button>
            </form>

            <p> Already have an account? <a href=''>Log in</a></p>

        </div>
    )
}

export default SignUp;
